/*
This is the main configuration file for the BIND DNS server, 
which is only used to include all other configuration files.
*/

include "/etc/bind/named.conf.options";

include "/etc/bind/named.conf.local";

include "/etc/bind/named.conf.default-zones";

include "/etc/bind/named.conf.logging";
